[openai]
api_key = ""
assistant_key = "asst_VpVEYDp6jGDgnMsELF65KAor"
assistant_key_sf = "asst_4CL8RZJcsgG84JSR5CcNcDwW"
assistant_key_json_schema = "asst_K1CcnQHT6HCrBGEWiAf89mJD"
assistant_key_docstring = "asst_7QLZrRg2BnpJGwC28WwDEAH3"

[assembly]
api_key = "16f91e9f91374b4194905334087febc1"

[salesforce]
sfuser = "michael.zozulia@almalasers.com"
sfcred = "EverlyQuinn#7665"
sftoken = "8VY2ZFvXya0eyI1oGCMOZeVc"


[powerautomate]
paSendEmail = "https://prod-82.westus.logic.azure.com:443/workflows/161736b6d81f439096d0452bd1c9b082/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=5qrhisEBUZH0Okbxxl0686qdj9-UyNpVo4fELrELPf8"
HTTP_URL_COMMS = "https://prod-82.westus.logic.azure.com:443/workflows/161736b6d81f439096d0452bd1c9b082/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=5qrhisEBUZH0Okbxxl0686qdj9-UyNpVo4fELrELPf8" 


[supabase]
SUPABASE_URL = "https://fujlgplcxuocbjiubmvx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1amxncGxjeHVvY2JqaXVibXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTc2MTIxMTIsImV4cCI6MjAxMzE4ODExMn0.PY5mkfQyjsI7YY-IDHhq2Ul88ZP9qLWgOtzrS3O9kUU"


[connections.supabase]
SUPABASE_URL = "https://rhmyeqaoqdqqcecygawp.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJobXllcWFvcWRxcWNlY3lnYXdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDE4NDk1NzksImV4cCI6MjAxNzQyNTU3OX0.gCZv8UHJii2aiLrYLib4Yn5PEFpAYUwKX11JsbiGzK0"


[zapier]
api_key = "sk-ak-WH14PbyWET9ZgoVWErGmT3zdDu"


[theodds]
api_key = "6b94ab1d81d71ea87b64473a1519fefd"

[tavily]
api_key = "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"


[other]
REPLICATE_API_KEY = "r8_3NSkiwpBKmC85pU61cXmYooqc35t5Ft0Dn5Cc"
SERP_API_KEY = '5cea8ad504d40e86139eeed0626cba900b102ed17704b48becabf94c2c0b0b99'
EXTRACTOR_API_KEY = '77da7c56abc8fa6c702c9d9644810ddc75c00b43'

